# Generated by Django 4.0 on 2021-12-16 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_de_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('recursos_adicionales', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(verbose_name='Valoración')),
                ('comentario', models.CharField(max_length=1000)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EncuestasApp.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EncuestasApp.modalidad'),
        ),
    ]
