# Generated by Django 4.0 on 2021-12-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncuestasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='recursos_adicionales',
            field=models.BooleanField(default=False),
        ),
    ]
